FROM node:20-alpine

WORKDIR /app

COPY server/package*.json ./server/

RUN npm install --prefix ./server

COPY server/ ./server/
COPY game/ ./game/

EXPOSE 55555

CMD ["./server/node_modules/.bin/nodemon", "./server/server.js"]
