sonar.projectKey=matheusperillo03_Trabalho-Individual-Gerencia-de-Configuracao-e-Evolucao-de-Software-2026-1-
sonar.organization=matheusperillo03
sonar.sources=server,game/src
sonar.exclusions=**/node_modules/**,server/tests/**,**/coverage/**
sonar.tests=server/tests
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
sonar.sourceEncoding=UTF-8
