apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mkjs
  namespace: mkjs
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mkjs.127.0.0.1.nip.io
      secretName: mkjs-tls
  rules:
    - host: mkjs.127.0.0.1.nip.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /socket.io
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
